// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnbouliiisjqyttxefir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuYm91bGlpaXNqcXl0dHhlZmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Nzc0MjgsImV4cCI6MjA2MjU1MzQyOH0.f44kWfAJ0h0kOi54Y3G2Xglh-YV1t0Y6wkdBY-Dy1P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);